# Generated by Django 4.0.5 on 2022-06-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sample_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='lastname',
            field=models.CharField(default='ddd', max_length=100),
            preserve_default=False,
        ),
    ]
