# Generated by Django 4.0.5 on 2022-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sample_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='firstname',
            field=models.CharField(default='kll', max_length=100),
            preserve_default=False,
        ),
    ]
