# Generated by Django 4.0.5 on 2022-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sample_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=10)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
            ],
        ),
    ]
